CATEGORIES = [
    "Reconnaissance",
    "Web Security",
    "Network",
    "Password Auditing",
    "Wireless",
    "Forensics",
    "OSINT",
    "Exploitation Labs",
    "Reverse Engineering",
    "Cryptography",
    "Sniffing & Spoofing",
    "Post Exploitation",
    "Malware Analysis",
    "Social Engineering",
]

CATEGORY_DESCRIPTIONS = {
    "Reconnaissance": "Information gathering and enumeration",
    "Web Security": "Web application testing and analysis",
    "Network": "Network scanning and analysis",
    "Password Auditing": "Password cracking and auditing",
    "Wireless": "Wireless network testing",
    "Forensics": "Digital forensics and analysis",
    "OSINT": "Open source intelligence gathering",
    "Exploitation Labs": "Exploitation frameworks and tools",
    "Reverse Engineering": "Binary analysis and reverse engineering",
    "Cryptography": "Cryptographic tools and analysis",
    "Sniffing & Spoofing": "Network traffic analysis and spoofing",
    "Post Exploitation": "Post-exploitation frameworks",
    "Malware Analysis": "Malware analysis and detection",
    "Social Engineering": "Social engineering tools",
}

CATEGORY_ICONS = {
    "Reconnaissance": "🔍",
    "Web Security": "🌐",
    "Network": "📡",
    "Password Auditing": "🔐",
    "Wireless": "📶",
    "Forensics": "🔎",
    "OSINT": "🕵",
    "Exploitation Labs": "💥",
    "Reverse Engineering": "⚙",
    "Cryptography": "🔑",
    "Sniffing & Spoofing": "📡",
    "Post Exploitation": "🎯",
    "Malware Analysis": "🦠",
    "Social Engineering": "🎭",
}
